
- name: Install NFS packages
  dnf:
    name: "{{ nfs_packages }}"
    state: present
  become: yes

- name: Create NFS directory
  file:
    path: /srv/nfs
    state: directory
  become: yes

- name: Adding master to /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.master }}"
  become: yes
  
- name: Adding workers to /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.workers }}"
  become: yes

- name: Enabled and start NFS service
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    masked: no
  become: yes
  
- name: Reload config from /etc/exports
  shell: exportfs -r
  become: yes

- name: Enabled services used by NFS nfs
  firewalld:
    service: nfs
    permanent: true
    state: enabled
  become: yes

- name: Enabled services used by NFS rpc-bind
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled
  become: yes

- name: Enabled services used by NFS mountd
  firewalld:
    service: mountd
    permanent: true
    state: enabled
  become: yes
  
- name: Reestarting the Firewalld service
  systemd:
    name: firewalld
    state: restarted
  become: yes
  