---

- name: Hostname configure
  hostname:
    name: "{{inventory_hostname}}.{{kubernets_domain}}"
    use: systemd
  when: inventory_hostname is regex("work*|master*")
  become: yes

- name: Adding DNS on all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}} {{item}}.{{kubernets_domain}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
  become: yes

- name: Updating system packages
  dnf:
    name: "*"
    state: latest
  become: yes
  
- name: Install utilities packages
  dnf:
    name: "{{ common_packages }}"
    state: present
  become: yes

- name: Configure TimeZone
  community.general.timezone:
    name: Europe/Madrid
  become: yes