---

- name: Running kubectl cluster info
  shell: "kubectl cluster-info"
  register: kubectl_info
  become: yes
  
- name: Showing information of Kubernetes Kluster
  debug:
    msg: "{{ kubectl_info.stdout_lines }}"

- name: Copy item of files
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: '0644'
  with_items:
    - "{{ files }}"
  become: yes

- name: Deployment appliations
  shell: "kubectl apply -f /root/{{ item }}"
  register: kubectl_apply_app
  with_items:
    - "{{ files }}"
  become: yes

- name: Showing desplyment result of appliations
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
    - "{{ kubectl_apply_app.results }}"

