---

- name: Disable the Swap memory
  shell: swapoff -a
  become: yes
  
- name: Comment the line of the swap partition of /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
  become: yes

- name: Restarting the server
  reboot:
  become: yes

- name: Enable the Kernel module br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  become: yes

- name: Enable masking in the public zone
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: public
  become: yes

- name: Configure AllowZoneDrifting=no in firewalld
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting='
    line: "AllowZoneDrifting=no"
    state: present
  become: yes
  
- name: Enable ports used by the SDN Flannel for Azure 8285 UDP
  firewalld:
    port: 8285/udp
    permanent: true
    state: enabled
  become: yes
  
- name: We enable ports used by the SDN Flannel for Azure 8472 UDP
  firewalld:
    port: 8472/udp
    permanent: true
    state: enabled
  become: yes

- name: Creating the file /etc/sysctl.d/k8s.conf
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: yes

- name: Reload all sysctl variables
  shell: sysctl --system
  become: yes
  
- name: Add the Docker repository
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
    warn: false
  become: yes

- name: Intall Docker
  dnf:
    name: "{{ docker_packages }}"
    state: present
  become: yes

- name: Enable and start Docker server
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes
  
- name: Copy the Docker daemon.json to make sure the cgroupdriver is systemd
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0644'
  become: yes

- name: Reestarting Docker service
  systemd:
    name: docker
    state: restarted
  become: yes

- name: Configure Kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Official repository of Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl
  become: yes

- name: Install Kubernetes
  dnf:
    name: "{{ kubernetes_packages }}"
    state: present
    disable_excludes: Kubernetes
  become: yes

- name: Enable and start Kubernetes service.
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes
  