---
- debug:
    msg: "The CERT hash of master is: {{ cert_hash }}"
  when: cert_hash is defined

- debug:
    msg: "The toekn hash of master is: {{ token_hash }}"
  when: token_hash is defined
  
- debug:
    msg: "The IP of master is: {{ ip_master }}"
  when: ip_master is defined
  
- name: Enable the mandatory ports to join the 10250 cluster
  firewalld:
    port: 10250/tcp
    permanent: true
    zone: public
    state: enabled
  become: yes
  
- name: Enable the mandatory ports to join the 30000 32767 cluster
  firewalld:
    port: 30000-32767/tcp
    permanent: true
    zone: public
    state: enabled
  become: yes
  
- name: Reset Firewalld service
  systemd:
    name: firewalld
    state: restarted
  become: yes
  
- name: Show the commands of join of worker to master
  debug:
    msg: "will execute: kubeadm join {{ ip_master }}:6443 --token {{ token_hash }} --discovery-token-ca-cert-hash sha256:{{ cert_hash }}"

- name: Joint Worker to kubernetes cluster
  shell: "kubeadm join {{ ip_master }}:6443 --token {{ token_hash }} --discovery-token-ca-cert-hash sha256:{{ cert_hash }}"
  register: kubeadm_join
  become: yes
  
- name: RResult of join
  debug:
    msg: "{{ kubeadm_join.stdout_lines }}"
  